### ISSUE TITLE
миниБаг

### ISSUE THREAD

**Issue by shikulja** [PopovEvgeniy/easykms#1]
При распаковки из архива (winrar) напрямую (в temp) не подцепляет список серверов.

**Comment by PopovEvgeniy** [comment]
И не должен. Список серверов грузиться из файла servers.txt, который при вашем способе не попадает в каталог temp. Распакуйте архив полностью в какой-нибудь каталог и запускайте программу оттуда

**Comment by shikulja** [comment]
должен попадать, так как при распаковке .exe распаковываются все файлы архива, во временную директорию
